### ISSUE TITLE
androidInjector has not been initialized

### ISSUE THREAD

**Issue by AdrianLeeElder** [nlgtuankiet/dagger-workmanager#3]
Hello. I'm having an issue starting up my second worker that uses the `ContextInjector` class.

```
dagger2 version: 2.28
assisted inject version: 0.5.2
```
I'm getting:

```
2020-06-07 10:07:09.009 5632-5895/com.company.myapp E/WM-WorkerFactory: Could not instantiate com.company.myapp.tasks.VideoBorderWorker
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:96)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:242)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property androidInjector has not been initialized
        at com.company.myapp.MainApplication.androidInjector(MainApplication.kt:30)
        at com.company.myapp.tasks.ContextInjection.inject(VideoBorderWorker.kt:22)
        at com.company.myapp.tasks.VideoBorderWorker.<init>(VideoBorderWorker.kt:30)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:96) 
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:242) 
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136) 
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2020-06-07 10:07:09.009 5632-5895/com.company.myapp E/WM-WorkerWrapper: Could not create Worker com.company.myapp.tasks.VideoBorderWorker
```

I have a main `MainApplication` component:
```java
class MainApplication : Application(), Configuration.Provider, HasAndroidInjector {
    @Inject
    lateinit var androidInjector: DispatchingAndroidInjector<Any>
    @Inject
    lateinit var appComponent: ApplicationComponent

    override fun onCreate() {
        appComponent = DaggerApplicationComponent.create()
        appComponent.inject(this)
        super.onCreate()
    }

    override fun androidInjector(): AndroidInjector<Any> {
        return androidInjector
    }

    override fun getWorkManagerConfiguration(): Configuration {
        val factory: DiInjectWorkerFactory = appComponent.factory()
        return Configuration.Builder().setWorkerFactory(factory).build()
    }
}
```

My `ApplicationComponent` interface:
```java
@Component(
        modules = [
            AndroidInjectionModule::class,
            VideoBorderWorker.Module::class,
            SampleAssistedInjectModule::class,
            WorkerBindingModule::class,
            MainModule::class
        ]
)
interface ApplicationComponent : AndroidInjector<Application> {
    fun factory(): DiInjectWorkerFactory
    fun inject(videoPublishActivity: VideoPublishActivity)
}

@Module(includes = [AssistedInject_SampleAssistedInjectModule::class])
@AssistedModule
interface SampleAssistedInjectModule

@MapKey
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
annotation class WorkerKey(val value: KClass<out ListenableWorker>)

@Module
interface WorkerBindingModule {
    @Binds
    @IntoMap
    @WorkerKey(ResizeVideoWorker::class)
    fun bindResizeVideoWorker(factory: Factory): ChildWorkerFactory
}
```
`ResizeVideoWorker`:

```java
class ResizeVideoWorker @AssistedInject constructor(
        @Assisted private val appContext: Context,
        @Assisted private val params: WorkerParameters,
        private val projectFileService: ProjectFileService,
        private val ffmpegService: FfmpegService
) : Worker(appContext, params) {

   ...

    @AssistedInject.Factory
    interface Factory : ChildWorkerFactory
}

interface ChildWorkerFactory {
    fun create(appContext: Context, params: WorkerParameters): ListenableWorker
}
```
And `VideoBorderWorker`:

```
object ContextInjection {
    @JvmStatic
    fun inject(to: Any, with: Context) {
        (with.applicationContext as HasAndroidInjector).androidInjector().inject(to)
    }
}

class VideoBorderWorker constructor(context: Context, params: WorkerParameters) : Worker(context, params) {
    @Inject lateinit var ffmpegService: FfmpegService

    init {
        ContextInjection.inject(to = this, with = context)
    }
   ...
    @dagger.Module
    interface Module {
        @ContributesAndroidInjector
        fun worker(): VideoBorderWorker
    }
}
```

**Comment by AdrianLeeElder** [comment]
Looks like I needed to use `DaggerAppCompatActivity` instead of `AppCompatActivity`. I'll go ahead and close this.
