### ISSUE TITLE
Upgrading WorkManager to latest version (2.6.0.XX) breaks the functionality !

### ISSUE THREAD

**Issue by shadygoneinsane** [nlgtuankiet/dagger-workmanager#4]
I am trying to use Work manager with the latest versions but it seems to work only till 2.5.0. 
I am not sure if something broke for 2.6.0.XX versions. 

The issue is only with HelloWorldWorker. 
Find the logs below : 

```
2021-07-23 23:38:15.983 17783-17910/com.sample.daggerworkmanagersample E/WM-WorkerFactory: Could not instantiate com.sample.daggerworkmanagersample.HelloWorldWorker
    java.lang.NoSuchMethodException: <init> [class android.content.Context, class androidx.work.WorkerParameters]
        at java.lang.Class.getConstructor0(Class.java:2327)
        at java.lang.Class.getDeclaredConstructor(Class.java:2166)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2021-07-23 23:38:15.983 17783-17910/com.sample.daggerworkmanagersample E/WM-WorkerWrapper: Could not create Worker com.sample.daggerworkmanagersample.HelloWorldWorker
```

While the `DaggerAndroidWorker` seems to work fine!

**Comment by nlgtuankiet** [comment]
I'll take a look into it, thank you for report this issue

**Comment by nlgtuankiet** [comment]
Fixed in this commit: https://github.com/nlgtuankiet/dagger-workmanager/pull/5/commits/e4a7b8628ce7669be5388853e0ac8071d149ed86
Turn out, in WorkManager 2.6.0-rc01 WorkManager uses AndroidX App Startup library for initialization. Previously, it used its own ContentProvider for init, which is disabled in our old codebase. Since the new Initializer is not disabled WorkManager init with the default configuration (without our custom WorkerFactory) hence HelloWorldWorker cannot instantiated.
